<?xml version="1.0"?>
<package format="2">
  <name>mbzirc2020_task2</name>
  <version>1.0.1</version>
  <description>The mbzirc2020_task2 package</description>

  <maintainer email="chou@jsk.imi.i.u-tokyo.ac.jp">Moju Zhao</maintainer>

  <license>BSD</license>


  <url type="website">http://www.jsk.t.u-tokyo.ac.jp/</url>

  <buildtool_depend>catkin</buildtool_depend>

  <exec_depend>mbzirc2020_task2_common</exec_depend>
  <exec_depend>mbzirc2020_task2_simulation</exec_depend>
  <exec_depend>mbzirc2020_task2_tasks</exec_depend>

  <export>
    <metapackage/>
  </export>
</package>
