# Valve Task Parameters

debug_view: true # for debug in dragon interface (gopos convergence)

valve_type: 3bridges # x in 'xbriges' denotes the number of bridges from the stem center to handle ring.
valve_pose_topic: /valve/mocap/pose

baselink_name: fc
cog_name: cog
end_effector_name: gripper

joint:
  conv_thresh: 0.017 # rad

approach:
  tip_offset: [0.025, 0, 0.18] # TODO: too heusritic
  pos_conv_thresh: 0.06 # m
  yaw_conv_thresh: 0.1  # rad
  att_conv_thresh: 0.06 # rad

adjust:
  tip_offset: [0.025, 0, 0.02] # TODO: too heuristic
  pos_conv_thresh: 0.08 # m
  yaw_conv_thresh: 0.1  # rad
  att_conv_thresh: 0.1 # rad

contact:
  rate: 10.0
  angular_velocity: 0.2
  init_torque: 0.1 # Nm
  incre_torque_rate: 0.2 # 0.1 is OK # Nm/s
  move_thresh: 0.1 # rad. angle change of valve
  check_interval: 4.0 # s. check the contact between robot and valve interval

manipulate:
  angular_velocity: 0.8 #0.5 # rad/s
  round_num: 2
  rate: 20.0 # Hz, 20 Hz is better than 40Hz, since the control rate is 40Hz, check with the yaw control terms (I terms) in upward valve case
  action: open #open # workaround to designate the open/close action
  fixed_traj: false # whether fixed the radius of the manipulating circle trajectory
  roll_moment_thresh: 0.2
  torque_adjust_roll_k: 0.01
  torque_adjust_yaw_k: 1.0
  torque_limit: 3.0
  yaw_velocity_thresh: 0.05 #0.1 # diff between true and target yaw velocity

finish:
  tip_z_offset: 0.2
